# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprof.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0002_userprofile_problems_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=userprof.models.user_images_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
