# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-05 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0003_auto_20170704_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='problems_solved',
        ),
    ]
