# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-29 22:39
from __future__ import unicode_literals

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_problem_sample_io'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_io',
            field=models.FileField(null=True, upload_to=contest.models.sample_io_upload),
        ),
    ]
