# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-30 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_problem_sample_io'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='sample_io',
        ),
    ]
