# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-30 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_remove_problem_sample_io'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name_of_contest',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
