# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20170630_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name_of_problem',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
