# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-30 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20170630_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='statement',
            field=tinymce.models.HTMLField(default=datetime.datetime(
                2017, 6, 30, 20, 47, 57, 848591, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
