# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-30 21:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_problem_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
