# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-05 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0003_auto_20170704_0023'),
        ('contest', '0010_problem_solved_by_whom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solved_by_whom',
        ),
        migrations.AddField(
            model_name='problem',
            name='solved_by_whom',
            field=models.ManyToManyField(null=True, to='userprof.UserProfile'),
        ),
    ]
