# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutioncode',
            name='code_text',
            field=models.FileField(null=True, upload_to='solutions/'),
        ),
    ]
